# Mapeo Maestro de Propiedad - Mercado Eléctrico Chileno (Marzo 2026)
# Auditoría realizada bajo protocolos de CMF, CEN y FNE.

diccionario_maestro_666 = {
    # LOTE 1
    "Arcadia Generación Solar S.A.": "Sonnedix",
    "Parque Eólico El Arrayán SpA": "Sonnedix",
    "PFV Ayla Solar SpA": "oEnergy",
    "Asesorías G-51 SpA": "Asesorías G-51 / Independiente",
    "Antu Energy SpA": "PMGD Holdco SpA",
    "Andrómeda Solar SpA": "Empresas Copec",
    "Generadora Antilhue Spa": "Independiente / Desarrollador PMGD",
    "Avilés SpA": "Independiente / Desarrollador PMGD",
    "AustrianSolar Chile Cuatro SpA": "AustrianSolar",
    "Aurora Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Aurora SpA": "Independiente / Desarrollador PMGD",
    "Atria Energía SpA": "Atria Energía",
    "AS Energía Ltda.": "Independiente / Desarrollador PMGD",
    "Arauco Bioenergía SpA": "Empresas Copec",
    "Anumar Energía del Sol 1 SpA": "Anumar",
    "Angol Solar I SpA": "Independiente / Desarrollador PMGD",
    "Andina Solar 13 SpA": "Matrix Renewables",
    "ANDINA SOLAR 2 SPA": "Matrix Renewables",
    "ANDINA SOLAR 1 SPA": "Matrix Renewables",
    "Andina Solar 10 SpA": "Matrix Renewables",
    "Andina Solar 17 Este SpA": "Matrix Renewables",
    "Andina Solar 6 SpA": "Matrix Renewables",
    "AES Andes S.A.": "AES Corporation",
    "Andes Solar II SpA": "AES Corporation",
    "Andes Solar III SpA": "AES Corporation",
    "Andes Solar IV SpA": "AES Corporation",
    "Empresa Eléctrica Angamos SpA": "AES Corporation",
    "Atacama Solar SpA": "Sonnedix",
    "AASA Energía S.A.": "Agrícola Ariztía (AASA)",
    "Abastible S.A.": "Empresas Copec",
    "Acciona Energía Chile Holdings S.A.": "Acciona Energía",
    "Acierta Energía SpA": "Acierta Energía",
    "Aela Generación S.A.": "Innergex",
    "Aggreko Chile Limitada": "Aggreko",
    "Agrícola Ancalí Limitada": "Grupo Bethia",
    "Agrosolar IV SpA": "Independiente / Desarrollador PMGD",
    "Agrosolar V SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctricas Aguas del Melado SpA": "Aguas del Melado / Independiente",
    "Aguas Andinas S.A.": "Veolia / IAM",
    "Ailin Fotovoltaica SpA": "Independiente / Desarrollador PMGD",
    "Alba SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Alcaldesa SpA": "Independiente / Desarrollador PMGD",
    "Algarrobo SpA": "Independiente / Desarrollador PMGD",
    "Hidroelectrica Allipén S.A.": "Independiente / Desarrollador ERNC",
    "Alto Cautín SpA": "Independiente / Desarrollador ERNC",
    "Alto Maipo SpA": "AES Corporation",
    "Sunenergreen S.A.": "Sunenergreen / Independiente",
    "Amanecer Solar SpA": "Brookfield Asset Management",
    "Andes Solar SpA": "AES Corporation",
    "Andes Generación SpA": "Andes Generación",
    "Baobab Energías Renovables SpA": "CVE (Cap Vert Energie)",
    "Compañía Barrick Chile Generación SpA": "Barrick Gold",
    "Bioenergías Forestales SpA": "Empresas CMPC",
    "Belén Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Bellavista SpA": "Independiente / Desarrollador PMGD",
    "Belloto SpA": "Independiente / Desarrollador PMGD",
    "Bepatagonia Generación S.A.": "Independiente",
    "Besalco Energía Renovable S.A.": "Besalco",
    "BESS del Desierto SpA": "Atlas Renewable Energy",
    "Betel SpA": "Independiente / Desarrollador PMGD",
    "Bio Energía Molina SpA": "Independiente / Desarrollador ERNC",
    "PMGD Bio Bio Negrete S.A.": "Independiente / Desarrollador PMGD",
    "Biocruz Generación S.A.": "Independiente / Bioenergía",
    "Blu Solar SpA": "Independiente / Desarrollador PMGD",
    "Blue Solar Doce SpA": "Korkia",
    "Blue Solar Ocho SpA": "Korkia",
    "Blue Solar Uno SpA": "Korkia",
    "Bluegate Energía SpA": "Independiente",
    "BTG Pactual Chile SpA": "BTG Pactual",
    "Parque Eólico Cabo Leones I S.A.": "Ibereólica / Repsol",

    # LOTE 2
    "Ibereólica Cabo Leones II S.A.": "Ibereólica / Naturgy (GPG)",
    "PE Cabo Leones III SpA": "Ibereólica / Repsol",
    "Cabrero Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora Calafate SpA": "Independiente / Desarrollador PMGD",
    "Calama Solar 1 SpA": "EQT / Solarpack",
    "Calbuco de Verano SpA": "Verano Energy",
    "Caldera Solar SpA": "Independiente / Desarrollador PMGD",
    "Callaqui de Verano SpA": "Verano Energy",
    "PMGD Calle Larga SpA": "Independiente / Desarrollador PMGD",
    "Campo Lindo SpA": "AES Corporation",
    "Candelaria Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Cantillana SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctrica Capullo S.A.": "Independiente / Minigeneración",
    "Capurata del Verano SpA": "Verano Energy",
    "Carbomet Energía S.A.": "Grupo Claro / Electra",
    "Carbon Free Chile SpA": "CarbonFree Technology",
    "Central Cardones S.A.": "Inkia Energy (Prime Energía)",
    "Empresa Eléctrica Carén S.A.": "Independiente / Minigeneración",
    "Planeta Investments SpA": "Planeta Investments",
    "Catemu Solar SpA": "Independiente / Desarrollador PMGD",
    "Cauce Solar SpA": "Independiente / Desarrollador PMGD",
    "Cbb Cales S.A.": "Grupo CBB (Cementos Bío Bío)",
    "CE Centinela Solar SpA": "Grenergy Renovables",
    "CE Uribe de Antofagasta Solar SpA": "Grenergy Renovables",
    "Cefalú Solar SpA": "Independiente / Desarrollador PMGD",
    "Centauro Solar SpA": "Independiente / Desarrollador PMGD",
    "Central El Atajo SpA": "Independiente / Desarrollador PMGD",
    "Cerro Dominador CSP S.A.": "Grupo Cerro (EIG Global Energy Partners)",
    "CFC HOLDINGS SPA": "CarbonFree Technology",
    "CGE Comercializadora SpA": "State Grid Corporation of China (SGCC)",
    "Central Hidroeléctrica Santa Elena S.A.": "Independiente / Minigeneración",
    "Sociedad Concesionaria Embalse Convento Viejo S.A.": "Concesionaria Convento Viejo",
    "Chacabuco Solar SpA": "Independiente / Desarrollador PMGD",
    "Pacific Hydro Chacayes S.A.": "State Power Investment Corporation (SPIC)",
    "Chapiquina Solar SpA": "Independiente / Desarrollador PMGD",
    "Chequen Solar SpA": "Independiente / Desarrollador PMGD",
    "Chester Solar I SpA": "Chester Solar",
    "Chester Solar IV SpA": "Chester Solar",
    "Chester Solar V SpA": "Chester Solar",
    "PMGD Chile Generación Ltda.": "Chile Generación",
    "Chilener II SpA": "Chilener",
    "Chronos Solar SpA": "Independiente / Desarrollador PMGD",
    "Chungungo S.A.": "Independiente / Desarrollador PMGD",
    "Chungungo Solar SpA": "Independiente / Desarrollador PMGD",
    "Cinergia Chile SpA": "Cinergia",
    "Ciprés SpA": "Independiente / Desarrollador PMGD",
    "Eléctrica Cipresillos SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Alfa SpA": "Independiente / Desarrollador PMGD",
    "Cocharcas Solar SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctrica Cochrane SpA": "AES Corporation",
    "Colbún S.A.": "Grupo Matte (Colbún)",
    "Energía Collil S.A.": "Independiente / Minigeneración",
    "Central Colmito S.A.": "Inkia Energy (Prime Energía)",
    "Comasa SpA": "Comasa",
    "Commonplace Energy SpA": "Commonplace Energy",
    "Cóndor Energía SpA": "Independiente / Minigeneración",
    "Conejo Solar SpA": "Arroyo Investors",
    "COPEC Renovables SpA": "Empresas Copec",
    "Copiapó Energía Solar SpA": "Copiapó Energía Solar",
    "Copiapó Solar SpA": "Enel Green Power",
    "Duero Energía Copiulemu SpA": "Duero Energía",
    "Corcovado de Verano SpA": "Verano Energy",
    "Cox Energy Comercializadora SpA": "Cox Energy",
    "Cuenca Solar SpA": "Independiente / Desarrollador PMGD",
    "Cumbres SpA": "Cumbres",
    "Sociedad Agrícola y Ganadera Curileufu Ltda.": "Curileufu",
    "CVE Proyecto Quince SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Siete SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Treinta y Cinco SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Treinta y Tres SpA": "CVE (Cap Vert Energie)",

    # LOTE 3
    "CVE Proyecto Treinta y Uno SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Veintiocho SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Veintiséis SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Veintiuno SpA": "CVE (Cap Vert Energie)",
    "Diego de Almagro Solar 3 S.A.": "Enel Chile",
    "Diego de Almagro Solar SpA": "Enel Chile",
    "Minicentral Hidroeléctrica El Diuto S.A.": "Independiente / Minigeneración",
    "Divisadero SpA.": "Independiente / Desarrollador PMGD",
    "Don Mariano Energy SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Don Flavio SpA": "Independiente / Desarrollador PMGD",
    "Parque Fotovoltaico Don Matías SpA": "Independiente / Desarrollador PMGD",
    "DOÑA ANTONIA SOLAR SPA": "Independiente / Desarrollador PMGD",
    "Doña Javiera Valledor SpA": "Independiente / Desarrollador PMGD",
    "Dongo Energía SpA": "Independiente / Desarrollador PMGD",
    "Hidroelectrica Dos Valles SpA": "Independiente / Minigeneración",
    "Dosal hnos y Cia Ltda": "Independiente / Agrícola-Generación",
    "Draco Solar SpA": "Independiente / Desarrollador PMGD",
    "Energía Atacama S.A.": "Independiente / Generación Térmica",
    "Eclipse Solar SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctrica La Compañía SpA": "Independiente / Minigeneración",
    "Energía Eólica San Matías SPA": "Independiente / Eólico",
    "Enel Green Power Chile S.A.": "Enel Chile",
    "Hidroeléctrica El Canelo S.A.": "Independiente / Minigeneración",
    "El Cóndor Solar SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica el Manzano S.A.": "Independiente / Minigeneración",
    "El Mirador SpA": "Independiente / Desarrollador PMGD",
    "El Agrio Hidro SpA": "Independiente / Minigeneración",
    "Empresa Eléctrica Tranquil SpA": "Independiente / Minigeneración",
    "PFV El Caiquén SpA": "oEnergy",
    "PFV El Carpintero SpA": "oEnergy",
    "PFV El Chercan SpA": "oEnergy",
    "Parque Solar El Conquistador SpA": "Independiente / Desarrollador PMGD",
    "PFV El Gaviotín SpA": "oEnergy",
    "Parque Fotovoltaico El Loreto SpA": "Independiente / Desarrollador PMGD",
    "PFV El Loro Choroy SpA": "oEnergy",
    "PFV El Mirlo SpA": "oEnergy",
    "Energía Cerro El Morado S.A.": "Independiente / Desarrollador PMGD",
    "Parque Eólico el Nogal SpA": "Independiente / Eólico",
    "El Pelícano Solar Company SpA": "TotalEnergies",
    "Empresa Eléctrica El Pinar SpA": "Independiente / Minigeneración",
    "PSF El Salitral S.A.": "Independiente / Desarrollador PMGD",
    "Eléctrica Moka SpA": "Independiente / Desarrollador PMGD",
    "Eléctrica Pinares Limitada": "Independiente / Minigeneración",
    "Elektra Generación S.A.": "Independiente / Comercialización",
    "Hidroeléctrica Embalse Ancoa SpA": "Independiente / Minigeneración",
    "Empresa Eléctrica Diego de Almagro SpA": "Enel Chile",
    "Empresa Eléctrica Vallenar S.A.": "Independiente / Generación",
    "EMOAC SpA": "Empresas Copec",
    "Empresa eléctrica Ciprés SpA": "Frontier Renewables",
    "Empresa Eléctrica Guindo Santo SpA": "Frontier Renewables",
    "Empresa Eléctrica Peumo SpA": "Frontier Renewables",
    "Empresa Eléctrica Raulí SpA": "Frontier Renewables",
    "Empresa Eléctrica Ventanas SpA": "AES Corporation",
    "Encina SpA": "Independiente / Desarrollador PMGD",
    "Energía Renovable Encino SpA": "Independiente / Desarrollador PMGD",
    "Enel Generación Chile S.A.": "Enel Chile",
    "Ener Services SpA": "Ener Services",
    "Enerbosch S.A.": "Grupo Bosch",
    "Energía Generación SpA": "Independiente / Generación",
    "Energía de La Patagonia y Aysén SpA": "Edelpa",
    "Energía Pacífico S.A.": "Grupo Casablanca",
    "Energía Renovable Roble SpA": "Independiente / Desarrollador PMGD",
    "Energía First SpA": "Independiente / Desarrollador PMGD",
    "Energía León S.A.": "Independiente / Generación",
    "Energía Morro Guayacán SpA": "Independiente / Desarrollador PMGD",
    "Energia Renovable Olmo SpA": "Independiente / Desarrollador PMGD",
    "Energía Siete SpA": "Independiente / Desarrollador PMGD",
    "Energias Pudidi SpA": "Independiente / Minigeneración",
    "EERM Energías del Futuro S.A.": "Independiente / Generación",
    "Energy Asset SpA": "Energy Asset",

    # LOTE 4
    "Energy Partners SpA": "Energy Partners",
    "Enernuevas S.A.": "Independiente / Desarrollador ERNC",
    "Enerquinta S.A.": "Chilquinta (State Grid Corporation of China)",
    "Engie Energía Chile S.A.": "Engie",
    "Enlasa Generación Chile S.A.": "Grupo Enlasa",
    "Enlight Investments SpA": "Enlight",
    "Enorchile S.A.": "Enorchile",
    "Eólica La Esperanza S.A.": "Independiente / Eólico",
    "Energía Eólica Los Olmos SpA": "Innergex",
    "Energía Renovable Rucapaine SpA": "Independiente / Minigeneración",
    "Energías Renovables Holding S.A.": "Independiente / Inversiones",
    "ENAP REFINERIAS S.A. - Aconcagua": "ENAP",
    "CVE Proyecto Nueve SpA": "CVE (Cap Vert Energie)",
    "Espinos S.A.": "Independiente / Minigeneración",
    "Generadora Estancilla SpA": "Independiente / Minigeneración",
    "Estepa Solar SpA": "Independiente / Desarrollador PMGD",
    "Estremera Energía SpA": "Independiente / Desarrollador PMGD",
    "EVOL SpA": "EVOL",
    "Factor Luz SpA": "Factor Luz",
    "Parque Fotovoltaico Faramalla SpA": "Independiente / Desarrollador PMGD",
    "Fardela Negra SpA": "Independiente / Desarrollador PMGD",
    "Farmdo Energy Chile SpA": "Farmdo Co., Ltd.",
    "Faro Corona SpA": "Independiente / Eólico",
    "Farol Solar SpA": "Independiente / Desarrollador PMGD",
    "Fénix Solar SpA": "Independiente / Desarrollador PMGD",
    "Fenster Energy Trading SpA": "Fenster",
    "PFV El Flamenco SpA": "Independiente / Desarrollador PMGD",
    "Florida Energía SpA": "Independiente / Minigeneración",
    "EnfraGen Chile Solar SpA": "EnfraGen (Glenfarne / Partners Group)",
    "SCL III SpA": "EnfraGen (Glenfarne / Partners Group)",
    "Forestal Neltume Carranco S.A.": "Grupo Vicini",
    "Fotovoltaica Cipres SpA": "oEnergy",
    "Fotovoltaica Faro III SpA": "Faro Energy",
    "Fotovoltaica Santa Rosario SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Valle Alegre SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Acacia SpA": "oEnergy",
    "Fotovoltaica Arrayan SpA": "oEnergy",
    "Fotovoltaica El Manzano SpA": "oEnergy",
    "Fotovoltaica Mañio SpA": "oEnergy",
    "Parque Fulgor SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Ariztía SpA": "Agrícola Ariztía (AASA)",
    "Apolo Solar SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Del Desierto SpA": "Independiente / Desarrollador PMGD",
    "El Castaño SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica de Los Andes SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Norte Grande 1 SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Norte Grande 5 SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Sol del Norte SpA": "Independiente / Desarrollador PMGD",
    "Gas Sur S.A.": "Grupo CGE / Naturgy",
    "Generación Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora Azul SpA": "Independiente / Minigeneración",
    "Generadora Ermitaño SpA": "Independiente / Minigeneración",
    "Piutel Generación Eléctrica Limitada": "Independiente",
    "Generadora Zapallar SpA": "Independiente",
    "Generadora Eléctrica Rhom Ltda": "Independiente",
    "Génova Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora del Pacífico SpA": "Independiente",
    "Geotérmica del Norte S.A.": "Enel Chile / ENAP",
    "Gestel Ingeniería Limitada": "Gestel",
    "GM Energy SpA": "Generadora Metropolitana (Inkia / AME)",
    "GM Holdings S.A.": "Generadora Metropolitana (Inkia / AME)",
    "Generadora Metropolitana SpA": "Generadora Metropolitana (Inkia / AME)",
    "Gestión de Proyectos Eléctricos S.A": "GPE",
    "GPG Generación Distribuida SpA": "Naturgy (Global Power Generation)",
    "GR Alerce Andino SpA": "Grenergy Renovables",
    "GR Chañar SpA": "Grenergy Renovables",
    "GR Guindo SpA": "Grenergy Renovables",
    "GR Liun SpA": "Grenergy Renovables",
    "GR Piñol SpA": "Grenergy Renovables",
    "GR Power Chile SpA": "Grenergy Renovables",

    # LOTE 5
    "GR Torres del Paine SpA": "Grenergy Renovables",
    "GR Algarrobo SpA": "Grenergy Renovables",
    "GR Araucaria SpA": "Grenergy Renovables",
    "GR Canelo SpA": "Grenergy Renovables",
    "GR Carza SpA": "Grenergy Renovables",
    "GR Chaquihue SpA": "Grenergy Renovables",
    "GR Ciprés SpA": "Grenergy Renovables",
    "GR Lleuque SpA": "Grenergy Renovables",
    "GR Pilo SpA": "Grenergy Renovables",
    "GR Pitao SpA": "Grenergy Renovables",
    "GR Ruil SpA": "Grenergy Renovables",
    "GR Tamarugo SpA": "Grenergy Renovables",
    "Granada SpA": "Independiente / Desarrollador PMGD",
    "GS Inima Chile S.A.": "GS Inima (Grupo GS)",
    "Guacolda Energía SpA": "Capital Advisors / WEG Capital",
    "Guadalupe Solar SpA": "Independiente / Desarrollador PMGD",
    "HBS Energía S.A.": "Grupo HBS",
    "Hidroeléctrica El Paso SpA": "Independiente / Minigeneración",
    "Bolero SpA": "EDF Renewables / Marubeni",
    "Hidroeléctrica Ensenada S.A.": "Independiente / Minigeneración",
    "Generadora Los Hibiscos SpA": "Independiente / Generación",
    "Hidroeléctrica Las Nieves SpA": "Independiente / Minigeneración",
    "Hidrocallao S.A.": "Independiente / Minigeneración",
    "Hidroeléctrica Don Eugenio SpA": "Independiente / Minigeneración",
    "Hidroeléctrica Los Corrales SpA": "Independiente / Minigeneración",
    "Hidroeléctrica Pichilonco S.A.": "Independiente / Minigeneración",
    "Hidroeléctrica San Andrés SpA": "Independiente / Minigeneración",
    "Hidroeléctrica Las Juntas S.A.": "Independiente / Minigeneración",
    "Hidroeléctrica Maisán SpA": "Independiente / Minigeneración",
    "Hidroeléctrica Trueno S.A.": "Independiente / Minigeneración",
    "Hidroenersur SpA": "Independiente / Minigeneración",
    "Hidroeléctrica Río Lircay S.A.": "Independiente / Minigeneración",
    "Hidromocho S.A.": "Independiente / Minigeneración",
    "Hidro Munilque SpA": "Independiente / Minigeneración",
    "Hidronalcas S.A.": "Independiente / Minigeneración",
    "Hidropaloma S.A.": "Independiente / Minigeneración",
    "Hormiga Solar SpA": "Independiente / Desarrollador PMGD",
    "Inversiones Hornitos SpA": "Engie",
    "Huemul Energía SpA": "Mainstream Renewable Power (Aker Horizons)",
    "Parque Fotovoltaico Idahuillo SpA": "Independiente / Desarrollador PMGD",
    "IEH Solar Chile SpA": "Independiente / Desarrollador PMGD",
    "Illalolen S.A.": "Independiente / Desarrollador PMGD",
    "Imelsa Energía SpA": "Imelsa Energía",
    "Incahuasi Energy SpA": "Independiente / Desarrollador PMGD",
    "Innovación Energía S.A.": "Grupo Enlasa",
    "Inmobiliaria Agua Marina S.A.": "Independiente / Generación",
    "Innergex Energía Renovable SpA": "Innergex",
    "Inversiones Fotovoltaicas SpA": "Independiente / Desarrollador PMGD",
    "Impulso Solar El Resplandor SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Itihue SpA": "Independiente / Desarrollador PMGD",
    "Jacarandá SpA": "Independiente / Desarrollador PMGD",
    "Javiera SpA": "Atlas Renewable Energy",
    "Joel Solar SpA": "Independiente / Desarrollador PMGD",
    "Juan Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora Eléctrica Kaltemp Ltda.": "Kaltemp",
    "KDM Energía S.A.": "Grupo KDM",
    "Hidroeléctrica La Confluencia S.A.": "Tinguiririca Energía (Pacific Hydro / Statkraft)",
    "Hidroeléctrica La Higuera S.A.": "Tinguiririca Energía (Pacific Hydro / Statkraft)",
    "La Huerta SPA": "Independiente / Desarrollador PMGD",
    "La Independencia Solar SpA": "Independiente / Desarrollador PMGD",
    "La Sierra SpA": "Independiente / Desarrollador PMGD",
    "La Acacia SpA": "Independiente / Desarrollador PMGD",
    "Generadora la Calera SpA": "Independiente / Generación",
    "La Chimba Bis SpA": "Independiente / Desarrollador PMGD",
    "La Gloria S.A.": "Independiente / Agrícola-Generación",
    "AustrianSolar Chile Seis SpA": "AustrianSolar",
    "Empresa Eléctrica La Leonera S.A.": "Independiente / Minigeneración",
    "Fotovoltaica La Ligua SpA": "Independiente / Desarrollador PMGD",
    "La Manga Energy SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Puma S.A.": "Independiente / Minigeneración",

    # LOTE 6
    "Hidroeléctrica Río Claro S.A.": "Independiente / Minigeneración",
    "Lágrimas del Sur SpA": "Independiente / Desarrollador PMGD",
    "Larqui Solar SpA": "Independiente / Desarrollador PMGD",
    "PFV Las Lechuzas SpA": "oEnergy",
    "RCL Solar SpA": "Independiente / Desarrollador PMGD",
    "PFV Las Cachañas SpA": "oEnergy",
    "PFV Las Catitas SpA": "oEnergy",
    "Las Chacras Energy SpA": "Independiente / Desarrollador PMGD",
    "Las Chilcas Solar SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Las Flores S.A.": "Independiente / Minigeneración",
    "PFV Las Golondrinas SpA": "oEnergy",
    "Bio Energía Las Pampas SpA": "Independiente / Bioenergía",
    "Eólico Las Peñas SpA": "Independiente / Eólico",
    "PFV Las Torcazas SpA": "oEnergy",
    "LASCAR ENERGY SPA": "Lascar Energy",
    "Laurel SpA": "Independiente / Desarrollador PMGD",
    "Los Libertadores Solar Spa": "Independiente / Desarrollador PMGD",
    "Lingue SpA": "Frontier Renewables",
    "Linxergy SpA": "Linxergy",
    "Linzor de Verano SpA": "Verano Energy",
    "Empresas Lipigas S.A.": "Lipigas",
    "Lirio de Campo Solar SpA": "Independiente / Desarrollador PMGD",
    "Lirios de Chumaquito SpA": "Independiente / Desarrollador PMGD",
    "Litre SpA": "Frontier Renewables",
    "Hidroeléctrica Lleuquereo S.A.": "Independiente / Minigeneración",
    "Parque Solar Lo Chacón SpA": "Independiente / Desarrollador PMGD",
    "Planta Solar Lo Miguel II SpA.": "Independiente / Desarrollador PMGD",
    "Loica SpA": "Independiente / Desarrollador PMGD",
    "PSF Lomas Coloradas S.A.": "Independiente / Desarrollador PMGD",
    "CIA Eléctrica los Morros S.A.": "Independiente / Minigeneración",
    "Los Sauces Solar I SpA": "Independiente / Desarrollador PMGD",
    "Los Sauces Solar II SpA": "Independiente / Desarrollador PMGD",
    "Parque Eólico Los Cururos SpA": "AES Corporation",
    "Los Guindos Generación SpA": "Inkia Energy (Prime Energía)",
    "Los Lagos SpA": "Statkraft",
    "Sociedad de Energías Renovables Los Lirios SpA": "Independiente / Desarrollador PMGD",
    "Solar Los Loros SpA": "Engie",
    "Los Molinos SpA": "Independiente / Desarrollador PMGD",
    "Los Padres Hidro SpA": "Independiente / Minigeneración",
    "Bio Energía Los Pinos SpA": "Independiente / Bioenergía",
    "Los Portones S.A.": "Independiente / Minigeneración",
    "Parque Solar Los Puquios SpA": "Independiente / Desarrollador PMGD",
    "Parque Fotovoltaico Ocoa II SpA": "Independiente / Desarrollador PMGD",
    "Luce Solar SpA": "Independiente / Desarrollador PMGD",
    "Luciano Solar SpA": "Independiente / Desarrollador PMGD",
    "Luna Energy SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Fotovoltaico Luz del Norte SpA": "First Solar / AES",
    "CIA Molinera Villarrica Ltda": "Molinera Villarrica",
    "MACAO SOLAR SPA": "Independiente / Desarrollador PMGD",
    "Magdalena Solar SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Mallarauco S.A.": "Independiente / Minigeneración",
    "Mandinga Solar SpA": "Independiente / Desarrollador PMGD",
    "Margarita Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora Eléctrica María Elena Ltda": "Independiente / Térmica",
    "Parque Solar Meco Chillan SpA": "Meco Solar",
    "Meli SpA": "Frontier Renewables",
    "Membrillo Solar SpA": "Independiente / Desarrollador PMGD",
    "Energía Eólica Mesamávida SpA": "Innergex",
    "MGM Innova Capital Chile SpA": "MGM Innova",
    "Miguel Solar SpA": "Independiente / Desarrollador PMGD",
    "Generadora Mimbre SpA": "Independiente / Minigeneración",
    "Minicentrales Araucanía S.A.": "Independiente / Minigeneración",
    "Konda Solar SpA": "Independiente / Desarrollador PMGD",
    "Eólica Monte Redondo SpA": "Engie / Nebras Power",
    "Suvan Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar La Muralla SpA": "Independiente / Desarrollador PMGD",
    "MVC Solar 17 SpA": "Independiente / Desarrollador PMGD",
    "MVC Solar 38 SpA": "Independiente / Desarrollador PMGD",
    "Mytilineos Energy Trading Chile SpA": "Mytilineos",
    "Neoelectra Energía Chile SpA": "Neoelectra",

    # LOTE 7
    "Neomas SpA": "Independiente / Desarrollador PMGD",
    "Newentun SpA": "Independiente / Desarrollador PMGD",
    "Nicolás Solar SpA": "Independiente / Desarrollador PMGD",
    "Noracid S.A.": "Grupo Ultramar / Noracid",
    "Norvind S.A.": "Statkraft",
    "Nextpower III Chile Holdco II SpA": "NextEnergy Capital",
    "Nueva Carena SpA": "Independiente / Desarrollador PMGD",
    "Generación de Energía Nueva Degan SpA": "Independiente / Minigeneración",
    "Eléctrica Nueva Energía s.a.": "Independiente / Generación",
    "Nueva Esperanza Solar SpA": "Independiente / Desarrollador PMGD",
    "Nuevo Amanecer FZ SpA": "Independiente / Desarrollador PMGD",
    "El Olivar Solar SpA": "Independiente / Desarrollador PMGD",
    "On-Group S.A.": "On-Group",
    "OPDENERGY Generación SpA": "Opdenergy (Antin Infrastructure Partners)",
    "Orafti Chile S.A.": "Beneo (Südzucker Group)",
    "Central Yungay S.A.": "Inkia Energy (Prime Energía)",
    "Orión Solar SpA": "Independiente / Desarrollador PMGD",
    "Osa Mayor Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Ovalle Norte SpA": "Independiente / Desarrollador PMGD",
    "Pacana del Verano SpA": "Verano Energy",
    "Pacific Hydro Chile S.A.": "SPIC (State Power Investment Corporation)",
    "Pacific SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Palacios SpA": "Independiente / Minigeneración",
    "Palpana de Verano SpA": "Verano Energy",
    "PSF Pama S.A.": "Independiente / Desarrollador PMGD",
    "Panguilemo SpA": "Independiente / Desarrollador PMGD",
    "Per Parinacota SpA": "Independiente / Desarrollador PMGD",
    "Parque Eólico Antofagasta SpA": "Independiente / Eólico",
    "Parque Fotovoltaico Doña Igna SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Alianza SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Benavente SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Solar Laurel SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Esmeralda SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Leyda SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Avellano SpA": "oEnergy",
    "Parque Solar Salamanca SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar San Isidro SpA": "Independiente / Desarrollador PMGD",
    "Planta Solar Santa Teresita II SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Tangua SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Viveros SpA": "Independiente / Desarrollador PMGD",
    "Parque Eólico Atacama SpA": "Independiente / Eólico",
    "Parque Eólico Lebu-Toro SpA": "Independiente / Eólico",
    "Parque Solar Cancha SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Colina SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar H6 SpA": "Independiente / Desarrollador PMGD",
    "Patricia Solar SpA": "Independiente / Desarrollador PMGD",
    "Parque Eólico Campo Lindo SpA": "AES Corporation",
    "Parque Eólico El Maitén SpA": "AES Corporation",
    "Parque Eólico Punta de Talca SpA": "Independiente / Eólico",
    "Pedro Solar SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctrica Pehuenche S.A.": "Enel Chile",
    "Generadora Eléctrica Pehui Ltda": "Independiente / Minigeneración",
    "Pelequén Sur SpA": "Independiente / Desarrollador PMGD",
    "Pesaro Solar SpA": "Independiente / Desarrollador PMGD",
    "Fotovoltaica Peumo SpA": "Independiente / Desarrollador PMGD",
    "Parque Fotovoltaico Alicahue Solar SpA": "Independiente / Desarrollador PMGD",
    "PFV El Rayador SpA": "oEnergy",
    "PFV Fragata SpA": "oEnergy",
    "PFV Las Taguas SpA": "oEnergy",
    "PFV Las Tortolas SpA": "oEnergy",
    "PFV Los Cisnes SpA": "oEnergy",
    "PFV El Chucao SpA": "oEnergy",
    "PFV El Cóndor SpA": "oEnergy",
    "PFV El Cuervo SpA": "oEnergy",
    "PFV El Piuquen SpA": "oEnergy",
    "PFV El Zorzal SpA": "oEnergy",
    "FV Santa Laura SpA": "Independiente / Desarrollador PMGD",
    "PFV Las Tencas SpA": "oEnergy",
    "PFV Lo Chacón SpA": "Independiente / Desarrollador PMGD",
    "PFV Los Tordos SpA": "oEnergy",

    # LOTE 8
    "PFV María Pinto SpA": "Independiente / Desarrollador PMGD",
    "Parque Fotovoltaico Nuevo Quillagua SpA": "Solek",
    "Maitén SpA": "Frontier Renewables",
    "Parque Fotovoltaico Ocoa SpA": "Independiente / Desarrollador PMGD",
    "Pacific Hydro Punta Sierra SpA": "SPIC (State Power Investment Corporation)",
    "Hidroeléctrica Piedras Negras SpA": "Independiente / Minigeneración",
    "Pilpilén SpA": "oEnergy",
    "Pingüino Emperador SpA": "oEnergy",
    "Piquero SpA": "oEnergy",
    "Pitra SpA": "Independiente / Desarrollador PMGD",
    "Planta Solar La Paz II SpA.": "Independiente / Desarrollador PMGD",
    "Planta Solar Peñaflor II SpA": "Independiente / Desarrollador PMGD",
    "Planta Solar San Pedro III SpA": "Independiente / Desarrollador PMGD",
    "Playero SpA": "oEnergy",
    "PMGD La Rosa de Sharon SpA": "Independiente / Desarrollador PMGD",
    "Pomerape SpA": "Independiente / Desarrollador PMGD",
    "Portezuelo SpA": "Independiente / Desarrollador PMGD",
    "Pozo Almonte Solar 1 SpA": "Independiente / Inversionistas Locales",
    "Pozo Almonte Solar 2 S.A.": "Enel Chile",
    "Pozo Almonte Solar 3 S.A.": "Enel Chile",
    "CVE Proyecto Dieciocho SpA": "CVE (Cap Vert Energie)",
    "PS La Brújula SpA": "Independiente / Desarrollador PMGD",
    "PS Maimalican SpA": "Independiente / Desarrollador PMGD",
    "Planta Solar Tocopilla SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Porvenir SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Santa Laura SpA": "Independiente / Desarrollador PMGD",
    "PSF Los Maitenes SpA": "Independiente / Desarrollador PMGD",
    "PSF San Ramón SpA": "Independiente / Desarrollador PMGD",
    "PSF Elizabeth SpA": "Independiente / Desarrollador PMGD",
    "PSF Santa Isabel SpA": "Independiente / Desarrollador PMGD",
    "Hidroelectrica Puclaro S.A.": "Independiente / Minigeneración",
    "Fotovoltaica Pueblo Hundido SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Pueblo Seco SpA": "Independiente / Desarrollador PMGD",
    "PMGD Puente SpA": "Independiente / Desarrollador PMGD",
    "Calama Solar 2 SpA": "EQT / Solarpack",
    "Hidroeléctrica Punta del Viento SpA": "Independiente / Minigeneración",
    "Punta Palmeras S.A.": "Acciona Energía",
    "PUNTIAGUDO ENERGY SPA": "Independiente / Desarrollador PMGD",
    "Eléctrica Puntilla S.A.": "Grupo Hurtado Vicuña (Puntilla)",
    "Parque Solar Catemu SpA": "Independiente / Desarrollador PMGD",
    "PV Salvador S.A.": "Atlas Renewable Energy",
    "Quemchi Generadora de Electricidad S.A.": "Independiente / Generación Regional",
    "Parque Solar Quetena S.A.": "Independiente / Desarrollador PMGD",
    "Prime Energía Quickstart SpA": "Inkia Energy (Prime Energía)",
    "Quillay Solar SpA": "Independiente / Desarrollador PMGD",
    "QUILMO SOLAR SPA": "Independiente / Desarrollador PMGD",
    "Quinta Solar SpA": "Independiente / Desarrollador PMGD",
    "Río Alto SpA": "Independiente / Minigeneración",
    "Ranguil SpA": "Independiente / Desarrollador PMGD",
    "Eléctrica Raso Power Ltda.": "Independiente / Generación",
    "Ravenna Solar SpA": "Independiente / Desarrollador PMGD",
    "Reden Cabildo Solar SpA": "Reden Solar",
    "Reden La Lajuela Solar SpA": "Reden Solar",
    "Reden Talhuen Solar SpA": "Reden Solar",
    "Las Mollacas SpA": "Independiente / Desarrollador PMGD",
    "La Chapeana SpA": "Independiente / Desarrollador PMGD",
    "Respaldo y Potencia SpA": "Independiente / Generación Térmica",
    "Parque Solar Retiro SpA": "Independiente / Desarrollador PMGD",
    "Rimini Solar SpA": "Independiente / Desarrollador PMGD",
    "FV Rinconada SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Río Huasco S.A.": "Independiente / Minigeneración",
    "Hidroeléctrica Río Colorado S.A.": "Independiente / Minigeneración",
    "El Peral SpA": "Independiente / Desarrollador PMGD",
    "Central Hidroeléctrica Río Mulchén S.A.": "Independiente / Minigeneración",
    "RLA Solar SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Robleria SpA": "Independiente / Minigeneración",
    "Parque Solar el Sauce SpA": "Independiente / Desarrollador PMGD",
    "RTN SOLAR SPA": "Independiente / Desarrollador PMGD",
    "RTS Energía S.A.": "RTS Energía",
    "RUBÉN SOLAR SPA": "Independiente / Desarrollador PMGD",

    # LOTE 9
    "Rucasol SpA": "Independiente / Desarrollador PMGD",
    "Empresa Eléctrica Rucatayo S.A.": "Statkraft",
    "Safira Energía Chile SpA": "Safira Energía (Brasil)",
    "Salado Energy SpA": "Independiente / Desarrollador PMGD",
    "PMGD Salerno SpA": "Independiente / Desarrollador PMGD",
    "Samo Bajo SpA": "Independiente / Desarrollador PMGD",
    "San Alfonso Solar SpA": "Independiente / Desarrollador PMGD",
    "San Marino Solar SpA": "Independiente / Desarrollador PMGD",
    "San Ramon Solar SpA": "Independiente / Desarrollador PMGD",
    "San Eugenio Solar SpA": "Independiente / Desarrollador PMGD",
    "San Francisco Solar SpA": "Independiente / Desarrollador PMGD",
    "San Juan S.A.": "Independiente / Minigeneración",
    "Parque Fotovoltaico Santa Adriana SpA": "Independiente / Desarrollador PMGD",
    "SANTA BARBARA ENERGY SPA": "Independiente / Desarrollador PMGD",
    "Santa Catalina Solar SpA": "Independiente / Desarrollador PMGD",
    "Santa Cecilia Solar SpA": "Independiente / Desarrollador PMGD",
    "Impulso Solar Las Lloysas SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Santa Cruz SpA": "Independiente / Desarrollador PMGD",
    "Santa Ester Solar SpA": "Independiente / Desarrollador PMGD",
    "CVE Proyecto Diecisiete SpA": "CVE (Cap Vert Energie)",
    "CVE Proyecto Seis SpA": "CVE (Cap Vert Energie)",
    "Consorcio Santa Marta S.A.": "Consorcio Santa Marta",
    "Santiago Solar S.A.": "EDF Renewables / Marubeni",
    "SAO PAULO SOLAR SPA": "Independiente / Desarrollador PMGD",
    "Asoc. de Canal. Sociedad del Canal de Maipo": "Asociación de Canalistas Sociedad del Canal de Maipo",
    "Sociedad Constructora de Obras Hidráulicas SpA": "Independiente",
    "SETF Energías Renovables SpA": "Independiente",
    "Sociedad Generadora Austral S.A.": "Grupo Austral / Independiente",
    "Siete Colores SpA": "Independiente / Desarrollador PMGD",
    "SLK CB Nueve SpA": "Solek",
    "Socer S.A.": "Independiente / Minigeneración",
    "Sociedad Energías Renovables El Álamo SpA": "Independiente / Desarrollador PMGD",
    "Energías Renovables El Boldo SpA": "Independiente / Desarrollador PMGD",
    "Socompa de Verano SpA": "Verano Energy",
    "Sol del sur 15 SpA": "Independiente / Desarrollador PMGD",
    "Parque Solar Fotovoltaico Sol del Desierto SpA": "Atlas Renewable Energy",
    "Sol del Sur 9 SpA": "Independiente / Desarrollador PMGD",
    "Solar TI Doce SpA": "Solek",
    "Solar TI Trece SpA": "Solek",
    "Solar Ti Treinta y Cuatro SpA": "Solek",
    "Solar TI Veinticuatro SpA": "Solek",
    "Solar Elena SpA": "Opdenergy (Antin Infrastructure Partners)",
    "PMGD Solar Los Perales I SpA": "Independiente / Desarrollador PMGD",
    "Solar TI Cuatro SpA": "Solek",
    "Solar TI Dieciséis SpA": "Solek",
    "Solar TI Diecisiete SpA": "Solek",
    "Solar TI Diez SpA": "Solek",
    "Solar TI Once SpA": "Solek",
    "Solar Ti Quince SpA": "Solek",
    "SOLAR TI TREINTA Y OCHO SPA": "Solek",
    "SOLAR TI TREINTA Y SEIS SPA": "Solek",
    "SOLAR TI TREINTA Y SIETE SpA": "Solek",
    "Solarity SpA": "Solarity",
    "Sonnedix Chile Inversiones 3 SpA": "Sonnedix",
    "Sonnedix Cox Energy Chile SpA": "Sonnedix",
    "Sonnedix Chile O&M Services SpA": "Sonnedix",
    "Sonnedix Metro Expansion SpA": "Sonnedix",
    "SPV P4 SpA": "Independiente / Desarrollador PMGD",
    "Statkraft Eolico S.A.": "Statkraft",
    "Sur Solar SpA": "Independiente / Desarrollador PMGD",
    "Sonnedix La Serena SpA": "Sonnedix",
    "Parque Solar Tabolango SpA.": "Independiente / Desarrollador PMGD",
    "Tacora Energy SpA": "Independiente / Desarrollador PMGD",
    "Parque Talinay Oriente S.A.": "Enel Chile",
    "Taltal Solar S.A.": "Enel Chile",
    "Tamakaya Energía SpA": "Solek",
    "Tamarico Solar Dos SpA": "Independiente / Desarrollador PMGD",
    "Tamarugal Solar 1 S.A.": "Independiente / Desarrollador PMGD",
    "Roberto Tamm y Cia Ltda.": "Roberto Tamm y Cia (Energía León)",
    "Taruca Solar SpA": "oEnergy",

    # LOTE 10
    "CVE Proyecto Ocho SpA": "CVE (Cap Vert Energie)",
    "Tauro Solar SpA": "Independiente / Desarrollador PMGD",
    "Tecnet S.A.": "State Grid Corporation of China (SGCC)",
    "TecnoRed S.A.": "State Grid Corporation of China (SGCC)",
    "Tedlar Mercurio SpA": "Tedlar / Independiente",
    "Tedlar Diemos SpA": "Tedlar / Independiente",
    "Tedlar Jupiter SpA": "Tedlar / Independiente",
    "Tedlar Luna SpA": "Tedlar / Independiente",
    "Teno III SpA": "Solarpack (EQT)",
    "Tielmes Energía SpA": "Independiente / Desarrollador PMGD",
    "Til Til Solar SpA": "Independiente / Desarrollador PMGD",
    "Toesca Renovables SpA": "Toesca Asset Management",
    "Toledo Solar SpA": "Independiente / Desarrollador PMGD",
    "Tórtola SpA": "oEnergy",
    "Tortuga Solar SpA": "Independiente / Desarrollador PMGD",
    "Hidroeléctrica Trailelfu SpA": "Independiente / Minigeneración",
    "Tralka SpA": "Independiente / Desarrollador PMGD",
    "Tricahue Solar SpA": "Independiente / Desarrollador PMGD",
    "Tricahue SpA": "Independiente / Desarrollador PMGD",
    "PFV El Trile SpA": "oEnergy",
    "TSGF SpA": "Independiente / Desarrollador ERNC",
    "Tucuquere SpA": "oEnergy",
    "Energías Ucuquer S.A.": "Ucuquer / Independiente",
    "Energías Ucuquer Dos S.A.": "Ucuquer / Independiente",
    "Parque Solar Unihue SpA": "Independiente / Desarrollador PMGD",
    "Valle de la Luna II SpA": "Atlas Renewable Energy",
    "Venezia Solar SpA": "Independiente / Desarrollador PMGD",
    "Verona Solar SpA": "Independiente / Desarrollador PMGD",
    "VESPA SOLAR SpA": "Independiente / Desarrollador PMGD",
    "Solar TI Dos SpA": "Solek",
    "Vientos de Renaico SpA": "Enel Chile",
    "Villaprat SpA": "Independiente / Desarrollador PMGD",
    "WPD Duqueco SpA": "WPD Chile",
    "WPD Malleco SpA": "WPD Chile",
    "WPD Negrete SpA": "WPD Chile",
    "Xue Solar SpA": "Independiente / Desarrollador PMGD"
}
import pandas as pd

# 1. Cargamos el diccionario (asegúrate de incluir la variable de arriba)
data = diccionario_maestro_666

# 2. Transformamos a DataFrame de Pandas
df = pd.DataFrame(list(data.items()), columns=['Razón Social', 'Holding / Ultimate Parent Entity (UPE)'])

# 3. Ordenamos alfabéticamente por Razón Social para mejor lectura
df = df.sort_values(by='Razón Social')
r = r"C:\Users\caraya.practica\OneDrive - Generadora Metropolitana\Escritorio\Mapeo_Propiedad_Generacion_Chile_2026.xlsx"
# 4. Exportamos a Excel
nombre_archivo = "Mapeo_Propiedad_Generacion_Chile_2026.xlsx"
df.to_excel(r, index=False)

#print(f"Éxito: Se ha generado el archivo '{nombre_archivo}' con {len(df)} registros.")